// AUTOMATICALLY GENERATED from the SPIR-V JSON grammar:
//   external/spirv.core.grammar.json.
// DO NOT MODIFY!

static GLSL_STD_450_INSTRUCTION_TABLE: &[ExtendedInstruction<'static>] = &[
    ext_inst!(GLOp, Round, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, RoundEven, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Trunc, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, FAbs, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, SAbs, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, FSign, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, SSign, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Floor, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Ceil, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Fract, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Radians, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Degrees, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Sin, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Cos, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Tan, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Asin, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Acos, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Atan, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Sinh, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Cosh, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Tanh, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Asinh, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Acosh, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Atanh, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Atan2, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, Pow, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, Exp, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Log, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Exp2, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Log2, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Sqrt, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, InverseSqrt, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Determinant, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, MatrixInverse, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Modf, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, ModfStruct, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, FMin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, UMin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, SMin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, FMax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, UMax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, SMax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        GLOp,
        FClamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GLOp,
        UClamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GLOp,
        SClamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GLOp,
        FMix,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GLOp,
        IMix,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GLOp, Step, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        GLOp,
        SmoothStep,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GLOp,
        Fma,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GLOp, Frexp, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, FrexpStruct, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Ldexp, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, PackSnorm4x8, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, PackUnorm4x8, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, PackSnorm2x16, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, PackUnorm2x16, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, PackHalf2x16, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, PackDouble2x32, [Float64], [], [(IdRef, One)]),
    ext_inst!(GLOp, UnpackSnorm2x16, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, UnpackUnorm2x16, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, UnpackHalf2x16, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, UnpackSnorm4x8, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, UnpackUnorm4x8, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, UnpackDouble2x32, [Float64], [], [(IdRef, One)]),
    ext_inst!(GLOp, Length, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, Distance, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, Cross, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, Normalize, [], [], [(IdRef, One)]),
    ext_inst!(
        GLOp,
        FaceForward,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GLOp, Reflect, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        GLOp,
        Refract,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GLOp, FindILsb, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, FindSMsb, [], [], [(IdRef, One)]),
    ext_inst!(GLOp, FindUMsb, [], [], [(IdRef, One)]),
    ext_inst!(
        GLOp,
        InterpolateAtCentroid,
        [InterpolationFunction],
        [],
        [(IdRef, One)]
    ),
    ext_inst!(
        GLOp,
        InterpolateAtSample,
        [InterpolationFunction],
        [],
        [(IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GLOp,
        InterpolateAtOffset,
        [InterpolationFunction],
        [],
        [(IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GLOp, NMin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GLOp, NMax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        GLOp,
        NClamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
];
