// AUTOMATICALLY GENERATED from the SPIR-V JSON grammar:
//   external/spirv.core.grammar.json.
// DO NOT MODIFY!

static GLSL_STD_450_INSTRUCTIONS: &[ExtendedInstruction<'static>] = &[
    ext_inst!(GL, GLOp, Round, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, RoundEven, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Trunc, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, FAbs, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, SAbs, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, FSign, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, SSign, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Floor, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Ceil, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Fract, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Radians, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Degrees, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Sin, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Cos, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Tan, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Asin, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Acos, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Atan, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Sinh, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Cosh, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Tanh, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Asinh, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Acosh, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Atanh, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Atan2, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, Pow, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, Exp, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Log, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Exp2, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Log2, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Sqrt, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, InverseSqrt, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Determinant, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, MatrixInverse, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Modf, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, ModfStruct, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, FMin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, UMin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, SMin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, FMax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, UMax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, SMax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        GL,
        GLOp,
        FClamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GL,
        GLOp,
        UClamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GL,
        GLOp,
        SClamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GL,
        GLOp,
        FMix,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GL,
        GLOp,
        IMix,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GL, GLOp, Step, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        GL,
        GLOp,
        SmoothStep,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GL,
        GLOp,
        Fma,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GL, GLOp, Frexp, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, FrexpStruct, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Ldexp, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, PackSnorm4x8, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, PackUnorm4x8, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, PackSnorm2x16, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, PackUnorm2x16, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, PackHalf2x16, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, PackDouble2x32, [Float64], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, UnpackSnorm2x16, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, UnpackUnorm2x16, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, UnpackHalf2x16, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, UnpackSnorm4x8, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, UnpackUnorm4x8, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, UnpackDouble2x32, [Float64], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Length, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, Distance, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, Cross, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, Normalize, [], [], [(IdRef, One)]),
    ext_inst!(
        GL,
        GLOp,
        FaceForward,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GL, GLOp, Reflect, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        GL,
        GLOp,
        Refract,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GL, GLOp, FindILsb, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, FindSMsb, [], [], [(IdRef, One)]),
    ext_inst!(GL, GLOp, FindUMsb, [], [], [(IdRef, One)]),
    ext_inst!(
        GL,
        GLOp,
        InterpolateAtCentroid,
        [InterpolationFunction],
        [],
        [(IdRef, One)]
    ),
    ext_inst!(
        GL,
        GLOp,
        InterpolateAtSample,
        [InterpolationFunction],
        [],
        [(IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        GL,
        GLOp,
        InterpolateAtOffset,
        [InterpolationFunction],
        [],
        [(IdRef, One), (IdRef, One)]
    ),
    ext_inst!(GL, GLOp, NMin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(GL, GLOp, NMax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        GL,
        GLOp,
        NClamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
];
pub static GLSL_STD_450_INSTRUCTION_TABLE: InstructionTable<ExtInstOp> =
    InstructionTable(GLSL_STD_450_INSTRUCTIONS, std::marker::PhantomData);
