// AUTOMATICALLY GENERATED from the SPIR-V JSON grammar:
//   external/spirv.core.grammar.json.
// DO NOT MODIFY!

static OPENCL_STD_100_INSTRUCTION_TABLE: &[ExtendedInstruction<'static>] = &[
    ext_inst!(CLOp, acos, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, acosh, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, acospi, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, asin, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, asinh, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, asinpi, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, atan, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, atan2, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, atanh, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, atanpi, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, atan2pi, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, cbrt, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, ceil, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, copysign, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, cos, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, cosh, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, cospi, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, erfc, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, erf, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, exp, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, exp2, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, exp10, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, expm1, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, fabs, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, fdim, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, floor, [], [], [(IdRef, One)]),
    ext_inst!(
        CLOp,
        fma,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, fmax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, fmin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, fmod, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, fract, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, frexp, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, hypot, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, ilogb, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, ldexp, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, lgamma, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, lgamma_r, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, log, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, log2, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, log10, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, log1p, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, logb, [], [], [(IdRef, One)]),
    ext_inst!(
        CLOp,
        mad,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, maxmag, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, minmag, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, modf, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, nan, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, nextafter, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, pow, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, pown, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, powr, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, remainder, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        remquo,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, rint, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, rootn, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, round, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, rsqrt, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, sin, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, sincos, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, sinh, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, sinpi, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, sqrt, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, tan, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, tanh, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, tanpi, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, tgamma, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, trunc, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_cos, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_divide, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, half_exp, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_exp2, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_exp10, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_log, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_log2, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_log10, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_powr, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, half_recip, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_rsqrt, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_sin, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_sqrt, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, half_tan, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_cos, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_divide, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, native_exp, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_exp2, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_exp10, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_log, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_log2, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_log10, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_powr, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, native_recip, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_rsqrt, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_sin, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_sqrt, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, native_tan, [], [], [(IdRef, One)]),
    ext_inst!(
        CLOp,
        fclamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, degrees, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, fmax_common, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, fmin_common, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        mix,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, radians, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, step, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        smoothstep,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, sign, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, cross, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, distance, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, length, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, normalize, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, fast_distance, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, fast_length, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, fast_normalize, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, s_abs, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, s_abs_diff, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, s_add_sat, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_add_sat, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, s_hadd, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_hadd, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, s_rhadd, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_rhadd, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        s_clamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CLOp,
        u_clamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, clz, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, ctz, [], [], [(IdRef, One)]),
    ext_inst!(
        CLOp,
        s_mad_hi,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CLOp,
        u_mad_sat,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CLOp,
        s_mad_sat,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, s_max, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_max, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, s_min, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_min, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, s_mul_hi, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, rotate, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, s_sub_sat, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_sub_sat, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_upsample, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, s_upsample, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, popcount, [], [], [(IdRef, One)]),
    ext_inst!(
        CLOp,
        s_mad24,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CLOp,
        u_mad24,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, s_mul24, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_mul24, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        vloadn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (LiteralInteger, One)]
    ),
    ext_inst!(
        CLOp,
        vstoren,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, vload_half, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        vload_halfn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (LiteralInteger, One)]
    ),
    ext_inst!(
        CLOp,
        vstore_half,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CLOp,
        vstore_half_r,
        [],
        [],
        [
            (IdRef, One),
            (IdRef, One),
            (IdRef, One),
            (FPRoundingMode, One)
        ]
    ),
    ext_inst!(
        CLOp,
        vstore_halfn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CLOp,
        vstore_halfn_r,
        [],
        [],
        [
            (IdRef, One),
            (IdRef, One),
            (IdRef, One),
            (FPRoundingMode, One)
        ]
    ),
    ext_inst!(
        CLOp,
        vloada_halfn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (LiteralInteger, One)]
    ),
    ext_inst!(
        CLOp,
        vstorea_halfn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CLOp,
        vstorea_halfn_r,
        [],
        [],
        [
            (IdRef, One),
            (IdRef, One),
            (IdRef, One),
            (FPRoundingMode, One)
        ]
    ),
    ext_inst!(CLOp, shuffle, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        shuffle2,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, printf, [], [], [(IdRef, One), (IdRef, ZeroOrMore)]),
    ext_inst!(CLOp, prefetch, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        bitselect,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CLOp,
        select,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CLOp, u_abs, [], [], [(IdRef, One)]),
    ext_inst!(CLOp, u_abs_diff, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CLOp, u_mul_hi, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CLOp,
        u_mad_hi,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
];
