// AUTOMATICALLY GENERATED from the SPIR-V JSON grammar:
//   external/spirv.core.grammar.json.
// DO NOT MODIFY!

static OPENCL_STD_100_INSTRUCTIONS: &[ExtendedInstruction<'static>] = &[
    ext_inst!(CL, CLOp, acos, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, acosh, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, acospi, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, asin, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, asinh, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, asinpi, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, atan, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, atan2, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, atanh, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, atanpi, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, atan2pi, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, cbrt, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, ceil, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, copysign, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, cos, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, cosh, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, cospi, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, erfc, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, erf, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, exp, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, exp2, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, exp10, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, expm1, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, fabs, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, fdim, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, floor, [], [], [(IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        fma,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, fmax, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, fmin, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, fmod, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, fract, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, frexp, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, hypot, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, ilogb, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, ldexp, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, lgamma, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, lgamma_r, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, log, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, log2, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, log10, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, log1p, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, logb, [], [], [(IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        mad,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, maxmag, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, minmag, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, modf, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, nan, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, nextafter, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, pow, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, pown, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, powr, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, remainder, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        remquo,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, rint, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, rootn, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, round, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, rsqrt, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, sin, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, sincos, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, sinh, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, sinpi, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, sqrt, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, tan, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, tanh, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, tanpi, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, tgamma, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, trunc, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_cos, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_divide, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, half_exp, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_exp2, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_exp10, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_log, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_log2, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_log10, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_powr, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, half_recip, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_rsqrt, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_sin, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_sqrt, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, half_tan, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_cos, [], [], [(IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        native_divide,
        [],
        [],
        [(IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, native_exp, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_exp2, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_exp10, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_log, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_log2, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_log10, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_powr, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, native_recip, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_rsqrt, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_sin, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_sqrt, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, native_tan, [], [], [(IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        fclamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, degrees, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, fmax_common, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, fmin_common, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        mix,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, radians, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, step, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        smoothstep,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, sign, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, cross, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, distance, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, length, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, normalize, [], [], [(IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        fast_distance,
        [],
        [],
        [(IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, fast_length, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, fast_normalize, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, s_abs, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, s_abs_diff, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, s_add_sat, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_add_sat, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, s_hadd, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_hadd, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, s_rhadd, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_rhadd, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        s_clamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        u_clamp,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, clz, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, ctz, [], [], [(IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        s_mad_hi,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        u_mad_sat,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        s_mad_sat,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, s_max, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_max, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, s_min, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_min, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, s_mul_hi, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, rotate, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, s_sub_sat, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_sub_sat, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_upsample, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, s_upsample, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, popcount, [], [], [(IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        s_mad24,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        u_mad24,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, s_mul24, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_mul24, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        vloadn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (LiteralInteger, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        vstoren,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, vload_half, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        vload_halfn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (LiteralInteger, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        vstore_half,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        vstore_half_r,
        [],
        [],
        [
            (IdRef, One),
            (IdRef, One),
            (IdRef, One),
            (FPRoundingMode, One)
        ]
    ),
    ext_inst!(
        CL,
        CLOp,
        vstore_halfn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        vstore_halfn_r,
        [],
        [],
        [
            (IdRef, One),
            (IdRef, One),
            (IdRef, One),
            (FPRoundingMode, One)
        ]
    ),
    ext_inst!(
        CL,
        CLOp,
        vloada_halfn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (LiteralInteger, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        vstorea_halfn,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        vstorea_halfn_r,
        [],
        [],
        [
            (IdRef, One),
            (IdRef, One),
            (IdRef, One),
            (FPRoundingMode, One)
        ]
    ),
    ext_inst!(CL, CLOp, shuffle, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        shuffle2,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        printf,
        [],
        [],
        [(IdRef, One), (IdRef, ZeroOrMore)]
    ),
    ext_inst!(CL, CLOp, prefetch, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        bitselect,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(
        CL,
        CLOp,
        select,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
    ext_inst!(CL, CLOp, u_abs, [], [], [(IdRef, One)]),
    ext_inst!(CL, CLOp, u_abs_diff, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(CL, CLOp, u_mul_hi, [], [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(
        CL,
        CLOp,
        u_mad_hi,
        [],
        [],
        [(IdRef, One), (IdRef, One), (IdRef, One)]
    ),
];
pub static OPENCL_STD_100_INSTRUCTION_TABLE: InstructionTable<ExtInstOp> =
    InstructionTable(OPENCL_STD_100_INSTRUCTIONS, std::marker::PhantomData);
