// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// AUTOMATICALLY GENERATED from the SPIR-V JSON grammar:
//   external/spirv.core.grammar.json.
// DO NOT MODIFY!

#[cfg_attr(rustfmt, rustfmt_skip)]
static OPENCL_STD_100_INSTRUCTION_TABLE: &'static [ExtendedInstruction<'static>] = &[
    ext_inst!(acos, 0, [], [(IdRef, One)]),
    ext_inst!(acosh, 1, [], [(IdRef, One)]),
    ext_inst!(acospi, 2, [], [(IdRef, One)]),
    ext_inst!(asin, 3, [], [(IdRef, One)]),
    ext_inst!(asinh, 4, [], [(IdRef, One)]),
    ext_inst!(asinpi, 5, [], [(IdRef, One)]),
    ext_inst!(atan, 6, [], [(IdRef, One)]),
    ext_inst!(atan2, 7, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(atanh, 8, [], [(IdRef, One)]),
    ext_inst!(atanpi, 9, [], [(IdRef, One)]),
    ext_inst!(atan2pi, 10, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(cbrt, 11, [], [(IdRef, One)]),
    ext_inst!(ceil, 12, [], [(IdRef, One)]),
    ext_inst!(copysign, 13, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(cos, 14, [], [(IdRef, One)]),
    ext_inst!(cosh, 15, [], [(IdRef, One)]),
    ext_inst!(cospi, 16, [], [(IdRef, One)]),
    ext_inst!(erfc, 17, [], [(IdRef, One)]),
    ext_inst!(erf, 18, [], [(IdRef, One)]),
    ext_inst!(exp, 19, [], [(IdRef, One)]),
    ext_inst!(exp2, 20, [], [(IdRef, One)]),
    ext_inst!(exp10, 21, [], [(IdRef, One)]),
    ext_inst!(expm1, 22, [], [(IdRef, One)]),
    ext_inst!(fabs, 23, [], [(IdRef, One)]),
    ext_inst!(fdim, 24, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(floor, 25, [], [(IdRef, One)]),
    ext_inst!(fma, 26, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(fmax, 27, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(fmin, 28, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(fmod, 29, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(fract, 30, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(frexp, 31, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(hypot, 32, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(ilogb, 33, [], [(IdRef, One)]),
    ext_inst!(ldexp, 34, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(lgamma, 35, [], [(IdRef, One)]),
    ext_inst!(lgamma_r, 36, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(log, 37, [], [(IdRef, One)]),
    ext_inst!(log2, 38, [], [(IdRef, One)]),
    ext_inst!(log10, 39, [], [(IdRef, One)]),
    ext_inst!(log1p, 40, [], [(IdRef, One)]),
    ext_inst!(logb, 41, [], [(IdRef, One)]),
    ext_inst!(mad, 42, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(maxmag, 43, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(minmag, 44, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(modf, 45, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(nan, 46, [], [(IdRef, One)]),
    ext_inst!(nextafter, 47, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(pow, 48, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(pown, 49, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(powr, 50, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(remainder, 51, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(remquo, 52, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(rint, 53, [], [(IdRef, One)]),
    ext_inst!(rootn, 54, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(round, 55, [], [(IdRef, One)]),
    ext_inst!(rsqrt, 56, [], [(IdRef, One)]),
    ext_inst!(sin, 57, [], [(IdRef, One)]),
    ext_inst!(sincos, 58, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(sinh, 59, [], [(IdRef, One)]),
    ext_inst!(sinpi, 60, [], [(IdRef, One)]),
    ext_inst!(sqrt, 61, [], [(IdRef, One)]),
    ext_inst!(tan, 62, [], [(IdRef, One)]),
    ext_inst!(tanh, 63, [], [(IdRef, One)]),
    ext_inst!(tanpi, 64, [], [(IdRef, One)]),
    ext_inst!(tgamma, 65, [], [(IdRef, One)]),
    ext_inst!(trunc, 66, [], [(IdRef, One)]),
    ext_inst!(half_cos, 67, [], [(IdRef, One)]),
    ext_inst!(half_divide, 68, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(half_exp, 69, [], [(IdRef, One)]),
    ext_inst!(half_exp2, 70, [], [(IdRef, One)]),
    ext_inst!(half_exp10, 71, [], [(IdRef, One)]),
    ext_inst!(half_log, 72, [], [(IdRef, One)]),
    ext_inst!(half_log2, 73, [], [(IdRef, One)]),
    ext_inst!(half_log10, 74, [], [(IdRef, One)]),
    ext_inst!(half_powr, 75, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(half_recip, 76, [], [(IdRef, One)]),
    ext_inst!(half_rsqrt, 77, [], [(IdRef, One)]),
    ext_inst!(half_sin, 78, [], [(IdRef, One)]),
    ext_inst!(half_sqrt, 79, [], [(IdRef, One)]),
    ext_inst!(half_tan, 80, [], [(IdRef, One)]),
    ext_inst!(native_cos, 81, [], [(IdRef, One)]),
    ext_inst!(native_divide, 82, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(native_exp, 83, [], [(IdRef, One)]),
    ext_inst!(native_exp2, 84, [], [(IdRef, One)]),
    ext_inst!(native_exp10, 85, [], [(IdRef, One)]),
    ext_inst!(native_log, 86, [], [(IdRef, One)]),
    ext_inst!(native_log2, 87, [], [(IdRef, One)]),
    ext_inst!(native_log10, 88, [], [(IdRef, One)]),
    ext_inst!(native_powr, 89, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(native_recip, 90, [], [(IdRef, One)]),
    ext_inst!(native_rsqrt, 91, [], [(IdRef, One)]),
    ext_inst!(native_sin, 92, [], [(IdRef, One)]),
    ext_inst!(native_sqrt, 93, [], [(IdRef, One)]),
    ext_inst!(native_tan, 94, [], [(IdRef, One)]),
    ext_inst!(s_abs, 141, [], [(IdRef, One)]),
    ext_inst!(s_abs_diff, 142, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(s_add_sat, 143, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_add_sat, 144, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(s_hadd, 145, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_hadd, 146, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(s_rhadd, 147, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_rhadd, 148, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(s_clamp, 149, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(u_clamp, 150, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(clz, 151, [], [(IdRef, One)]),
    ext_inst!(ctz, 152, [], [(IdRef, One)]),
    ext_inst!(s_mad_hi, 153, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(u_mad_sat, 154, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(s_mad_sat, 155, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(s_max, 156, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_max, 157, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(s_min, 158, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_min, 159, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(s_mul_hi, 160, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(rotate, 161, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(s_sub_sat, 162, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_sub_sat, 163, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_upsample, 164, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(s_upsample, 165, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(popcount, 166, [], [(IdRef, One)]),
    ext_inst!(s_mad24, 167, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(u_mad24, 168, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(s_mul24, 169, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_mul24, 170, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_abs, 201, [], [(IdRef, One)]),
    ext_inst!(u_abs_diff, 202, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_mul_hi, 203, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(u_mad_hi, 204, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(fclamp, 95, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(degrees, 96, [], [(IdRef, One)]),
    ext_inst!(fmax_common, 97, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(fmin_common, 98, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(mix, 99, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(radians, 100, [], [(IdRef, One)]),
    ext_inst!(step, 101, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(smoothstep, 102, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(sign, 103, [], [(IdRef, One)]),
    ext_inst!(cross, 104, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(distance, 105, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(length, 106, [], [(IdRef, One)]),
    ext_inst!(normalize, 107, [], [(IdRef, One)]),
    ext_inst!(fast_distance, 108, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(fast_length, 109, [], [(IdRef, One)]),
    ext_inst!(fast_normalize, 110, [], [(IdRef, One)]),
    ext_inst!(bitselect, 186, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(select, 187, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(vloadn, 171, [], [(IdRef, One), (IdRef, One), (LiteralInteger, One)]),
    ext_inst!(vstoren, 172, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(vload_half, 173, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(vload_halfn, 174, [], [(IdRef, One), (IdRef, One), (LiteralInteger, One)]),
    ext_inst!(vstore_half, 175, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(vstore_half_r, 176, [], [(IdRef, One), (IdRef, One), (IdRef, One), (FPRoundingMode, One)]),
    ext_inst!(vstore_halfn, 177, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(vstore_halfn_r, 178, [], [(IdRef, One), (IdRef, One), (IdRef, One), (FPRoundingMode, One)]),
    ext_inst!(vloada_halfn, 179, [], [(IdRef, One), (IdRef, One), (LiteralInteger, One)]),
    ext_inst!(vstorea_halfn, 180, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(vstorea_halfn_r, 181, [], [(IdRef, One), (IdRef, One), (IdRef, One), (FPRoundingMode, One)]),
    ext_inst!(shuffle, 182, [], [(IdRef, One), (IdRef, One)]),
    ext_inst!(shuffle2, 183, [], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    ext_inst!(printf, 184, [], [(IdRef, One), (IdRef, ZeroOrMore)]),
    ext_inst!(prefetch, 185, [], [(IdRef, One), (IdRef, One)]),
];
