// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This rust module is automatically generated from the SPIR-V JSON grammar:
//  https://raw.githubusercontent.com/KhronosGroup/SPIRV-Tools/master/source/spirv.core.grammar.json

#[allow(dead_code)]
#[derive(Clone, Copy, Debug)]
pub enum OperandKind {
    ImageOperands,
    FPFastMathMode,
    SelectionControl,
    LoopControl,
    FunctionControl,
    IdMemorySemantics,
    MemoryAccess,
    KernelProfilingInfo,
    SourceLanguage,
    ExecutionModel,
    AddressingModel,
    MemoryModel,
    ExecutionMode,
    StorageClass,
    Dim,
    SamplerAddressingMode,
    SamplerFilterMode,
    ImageFormat,
    ImageChannelOrder,
    ImageChannelDataType,
    FPRoundingMode,
    LinkageType,
    AccessQualifier,
    FunctionParameterAttribute,
    Decoration,
    BuiltIn,
    IdScope,
    GroupOperation,
    KernelEnqueueFlags,
    Capability,
    IdType,
    IdResult,
    IdRef,
    LiteralInteger,
    LiteralString,
    LiteralContextDependentNumber,
    LiteralExtInstInteger,
    LiteralSpecConstantOpInteger,
    PairLiteralIntegerIdRef,
    PairIdRefLiteralInteger
}

#[cfg_attr(rustfmt, rustfmt_skip)]
static INSTRUCTION_TABLE: &'static [Instruction<'static>] = &[
    inst!(Nop, [], []),
    inst!(Undef, [], [(IdType, One), (IdResult, One)]),
    inst!(SourceContinued, [], [(LiteralString, One)]),
    inst!(Source, [], [(SourceLanguage, One), (LiteralInteger, One), (IdRef, ZeroOrOne), (LiteralString, ZeroOrOne)]),
    inst!(SourceExtension, [], [(LiteralString, One)]),
    inst!(Name, [], [(IdRef, One), (LiteralString, One)]),
    inst!(MemberName, [], [(IdRef, One), (LiteralInteger, One), (LiteralString, One)]),
    inst!(String, [], [(IdResult, One), (LiteralString, One)]),
    inst!(Line, [], [(IdRef, One), (LiteralInteger, One), (LiteralInteger, One)]),
    inst!(Extension, [], [(LiteralString, One)]),
    inst!(ExtInstImport, [], [(IdResult, One), (LiteralString, One)]),
    inst!(ExtInst, [], [(IdType, One), (IdResult, One), (IdRef, One), (LiteralExtInstInteger, One), (IdRef, ZeroOrMore)]),
    inst!(MemoryModel, [], [(AddressingModel, One), (MemoryModel, One)]),
    inst!(EntryPoint, [], [(ExecutionModel, One), (IdRef, One), (LiteralString, One), (IdRef, ZeroOrMore)]),
    inst!(ExecutionMode, [], [(IdRef, One), (ExecutionMode, One)]),
    inst!(Capability, [], [(Capability, One)]),
    inst!(TypeVoid, [], [(IdResult, One)]),
    inst!(TypeBool, [], [(IdResult, One)]),
    inst!(TypeInt, [], [(IdResult, One), (LiteralInteger, One), (LiteralInteger, One)]),
    inst!(TypeFloat, [], [(IdResult, One), (LiteralInteger, One)]),
    inst!(TypeVector, [], [(IdResult, One), (IdRef, One), (LiteralInteger, One)]),
    inst!(TypeMatrix, [Matrix], [(IdResult, One), (IdRef, One), (LiteralInteger, One)]),
    inst!(TypeImage, [], [(IdResult, One), (IdRef, One), (Dim, One), (LiteralInteger, One), (LiteralInteger, One), (LiteralInteger, One), (LiteralInteger, One), (ImageFormat, One), (AccessQualifier, ZeroOrOne)]),
    inst!(TypeSampler, [], [(IdResult, One)]),
    inst!(TypeSampledImage, [], [(IdResult, One), (IdRef, One)]),
    inst!(TypeArray, [], [(IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(TypeRuntimeArray, [Shader], [(IdResult, One), (IdRef, One)]),
    inst!(TypeStruct, [], [(IdResult, One), (IdRef, ZeroOrMore)]),
    inst!(TypeOpaque, [Kernel], [(IdResult, One), (LiteralString, One)]),
    inst!(TypePointer, [], [(IdResult, One), (StorageClass, One), (IdRef, One)]),
    inst!(TypeFunction, [], [(IdResult, One), (IdRef, One), (IdRef, ZeroOrMore)]),
    inst!(TypeEvent, [Kernel], [(IdResult, One)]),
    inst!(TypeDeviceEvent, [DeviceEnqueue], [(IdResult, One)]),
    inst!(TypeReserveId, [Pipes], [(IdResult, One)]),
    inst!(TypeQueue, [DeviceEnqueue], [(IdResult, One)]),
    inst!(TypePipe, [Pipes], [(IdResult, One), (AccessQualifier, One)]),
    inst!(TypeForwardPointer, [Addresses], [(IdRef, One), (StorageClass, One)]),
    inst!(ConstantTrue, [], [(IdType, One), (IdResult, One)]),
    inst!(ConstantFalse, [], [(IdType, One), (IdResult, One)]),
    inst!(Constant, [], [(IdType, One), (IdResult, One), (LiteralContextDependentNumber, One)]),
    inst!(ConstantComposite, [], [(IdType, One), (IdResult, One), (IdRef, ZeroOrMore)]),
    inst!(ConstantSampler, [LiteralSampler], [(IdType, One), (IdResult, One), (SamplerAddressingMode, One), (LiteralInteger, One), (SamplerFilterMode, One)]),
    inst!(ConstantNull, [], [(IdType, One), (IdResult, One)]),
    inst!(SpecConstantTrue, [], [(IdType, One), (IdResult, One)]),
    inst!(SpecConstantFalse, [], [(IdType, One), (IdResult, One)]),
    inst!(SpecConstant, [], [(IdType, One), (IdResult, One), (LiteralContextDependentNumber, One)]),
    inst!(SpecConstantComposite, [], [(IdType, One), (IdResult, One), (IdRef, ZeroOrMore)]),
    inst!(SpecConstantOp, [], [(IdType, One), (IdResult, One), (LiteralSpecConstantOpInteger, One)]),
    inst!(Function, [], [(IdType, One), (IdResult, One), (FunctionControl, One), (IdRef, One)]),
    inst!(FunctionParameter, [], [(IdType, One), (IdResult, One)]),
    inst!(FunctionEnd, [], []),
    inst!(FunctionCall, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, ZeroOrMore)]),
    inst!(Variable, [], [(IdType, One), (IdResult, One), (StorageClass, One), (IdRef, ZeroOrOne)]),
    inst!(ImageTexelPointer, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(Load, [], [(IdType, One), (IdResult, One), (IdRef, One), (MemoryAccess, ZeroOrOne)]),
    inst!(Store, [], [(IdRef, One), (IdRef, One), (MemoryAccess, ZeroOrOne)]),
    inst!(CopyMemory, [], [(IdRef, One), (IdRef, One), (MemoryAccess, ZeroOrOne)]),
    inst!(CopyMemorySized, [Addresses], [(IdRef, One), (IdRef, One), (IdRef, One), (MemoryAccess, ZeroOrOne)]),
    inst!(AccessChain, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, ZeroOrMore)]),
    inst!(InBoundsAccessChain, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, ZeroOrMore)]),
    inst!(PtrAccessChain, [Addresses], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, ZeroOrMore)]),
    inst!(ArrayLength, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (LiteralInteger, One)]),
    inst!(GenericPtrMemSemantics, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(InBoundsPtrAccessChain, [Addresses], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, ZeroOrMore)]),
    inst!(Decorate, [], [(IdRef, One), (Decoration, One)]),
    inst!(MemberDecorate, [], [(IdRef, One), (LiteralInteger, One), (Decoration, One)]),
    inst!(DecorationGroup, [], [(IdResult, One)]),
    inst!(GroupDecorate, [], [(IdRef, One), (IdRef, ZeroOrMore)]),
    inst!(GroupMemberDecorate, [], [(IdRef, One), (PairIdRefLiteralInteger, ZeroOrMore)]),
    inst!(VectorExtractDynamic, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(VectorInsertDynamic, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(VectorShuffle, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (LiteralInteger, ZeroOrMore)]),
    inst!(CompositeConstruct, [], [(IdType, One), (IdResult, One), (IdRef, ZeroOrMore)]),
    inst!(CompositeExtract, [], [(IdType, One), (IdResult, One), (IdRef, One), (LiteralInteger, ZeroOrMore)]),
    inst!(CompositeInsert, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (LiteralInteger, ZeroOrMore)]),
    inst!(CopyObject, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(Transpose, [Matrix], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(SampledImage, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ImageSampleImplicitLod, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSampleExplicitLod, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, One)]),
    inst!(ImageSampleDrefImplicitLod, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSampleDrefExplicitLod, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, One)]),
    inst!(ImageSampleProjImplicitLod, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSampleProjExplicitLod, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, One)]),
    inst!(ImageSampleProjDrefImplicitLod, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSampleProjDrefExplicitLod, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, One)]),
    inst!(ImageFetch, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageGather, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageDrefGather, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageRead, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageWrite, [], [(IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(Image, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ImageQueryFormat, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ImageQueryOrder, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ImageQuerySizeLod, [Kernel, ImageQuery], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ImageQuerySize, [Kernel, ImageQuery], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ImageQueryLod, [ImageQuery], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ImageQueryLevels, [Kernel, ImageQuery], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ImageQuerySamples, [Kernel, ImageQuery], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ConvertFToU, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ConvertFToS, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ConvertSToF, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ConvertUToF, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(UConvert, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(SConvert, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(FConvert, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(QuantizeToF16, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ConvertPtrToU, [Addresses], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(SatConvertSToU, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(SatConvertUToS, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(ConvertUToPtr, [Addresses], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(PtrCastToGeneric, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(GenericCastToPtr, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(GenericCastToPtrExplicit, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One), (StorageClass, One)]),
    inst!(Bitcast, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(SNegate, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(FNegate, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(IAdd, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FAdd, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ISub, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FSub, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(IMul, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FMul, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(UDiv, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(SDiv, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FDiv, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(UMod, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(SRem, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(SMod, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FRem, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FMod, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(VectorTimesScalar, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(MatrixTimesScalar, [Matrix], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(VectorTimesMatrix, [Matrix], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(MatrixTimesVector, [Matrix], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(MatrixTimesMatrix, [Matrix], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(OuterProduct, [Matrix], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(Dot, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(IAddCarry, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ISubBorrow, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(UMulExtended, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(SMulExtended, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(Any, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(All, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(IsNan, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(IsInf, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(IsFinite, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(IsNormal, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(SignBitSet, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(LessOrGreater, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(Ordered, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(Unordered, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(LogicalEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(LogicalNotEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(LogicalOr, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(LogicalAnd, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(LogicalNot, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(Select, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(IEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(INotEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(UGreaterThan, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(SGreaterThan, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(UGreaterThanEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(SGreaterThanEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ULessThan, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(SLessThan, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ULessThanEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(SLessThanEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FOrdEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FUnordEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FOrdNotEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FUnordNotEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FOrdLessThan, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FUnordLessThan, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FOrdGreaterThan, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FUnordGreaterThan, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FOrdLessThanEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FUnordLessThanEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FOrdGreaterThanEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(FUnordGreaterThanEqual, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ShiftRightLogical, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ShiftRightArithmetic, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(ShiftLeftLogical, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(BitwiseOr, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(BitwiseXor, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(BitwiseAnd, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One)]),
    inst!(Not, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(BitFieldInsert, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(BitFieldSExtract, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(BitFieldUExtract, [Shader], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(BitReverse, [Shader], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(BitCount, [], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(DPdx, [Shader], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(DPdy, [Shader], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(Fwidth, [Shader], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(DPdxFine, [DerivativeControl], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(DPdyFine, [DerivativeControl], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(FwidthFine, [DerivativeControl], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(DPdxCoarse, [DerivativeControl], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(DPdyCoarse, [DerivativeControl], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(FwidthCoarse, [DerivativeControl], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(EmitVertex, [Geometry], []),
    inst!(EndPrimitive, [Geometry], []),
    inst!(EmitStreamVertex, [GeometryStreams], [(IdRef, One)]),
    inst!(EndStreamPrimitive, [GeometryStreams], [(IdRef, One)]),
    inst!(ControlBarrier, [], [(IdScope, One), (IdScope, One), (IdMemorySemantics, One)]),
    inst!(MemoryBarrier, [], [(IdScope, One), (IdMemorySemantics, One)]),
    inst!(AtomicLoad, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One)]),
    inst!(AtomicStore, [], [(IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicExchange, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicCompareExchange, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdMemorySemantics, One), (IdRef, One), (IdRef, One)]),
    inst!(AtomicCompareExchangeWeak, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdMemorySemantics, One), (IdRef, One), (IdRef, One)]),
    inst!(AtomicIIncrement, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One)]),
    inst!(AtomicIDecrement, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One)]),
    inst!(AtomicIAdd, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicISub, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicSMin, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicUMin, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicSMax, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicUMax, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicAnd, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicOr, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(AtomicXor, [], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One), (IdRef, One)]),
    inst!(Phi, [], [(IdType, One), (IdResult, One), (IdRef, ZeroOrMore)]),
    inst!(LoopMerge, [], [(IdRef, One), (IdRef, One), (LoopControl, One)]),
    inst!(SelectionMerge, [], [(IdRef, One), (SelectionControl, One)]),
    inst!(Label, [], [(IdResult, One)]),
    inst!(Branch, [], [(IdRef, One)]),
    inst!(BranchConditional, [], [(IdRef, One), (IdRef, One), (IdRef, One), (LiteralInteger, ZeroOrMore)]),
    inst!(Switch, [], [(IdRef, One), (IdRef, One), (PairLiteralIntegerIdRef, ZeroOrMore)]),
    inst!(Kill, [Shader], []),
    inst!(Return, [], []),
    inst!(ReturnValue, [], [(IdRef, One)]),
    inst!(Unreachable, [], []),
    inst!(LifetimeStart, [Kernel], [(IdRef, One), (LiteralInteger, One)]),
    inst!(LifetimeStop, [Kernel], [(IdRef, One), (LiteralInteger, One)]),
    inst!(GroupAsyncCopy, [Kernel], [(IdType, One), (IdResult, One), (IdScope, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GroupWaitEvents, [Kernel], [(IdScope, One), (IdRef, One), (IdRef, One)]),
    inst!(GroupAll, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (IdRef, One)]),
    inst!(GroupAny, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (IdRef, One)]),
    inst!(GroupBroadcast, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (IdRef, One), (IdRef, One)]),
    inst!(GroupIAdd, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (GroupOperation, One), (IdRef, One)]),
    inst!(GroupFAdd, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (GroupOperation, One), (IdRef, One)]),
    inst!(GroupFMin, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (GroupOperation, One), (IdRef, One)]),
    inst!(GroupUMin, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (GroupOperation, One), (IdRef, One)]),
    inst!(GroupSMin, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (GroupOperation, One), (IdRef, One)]),
    inst!(GroupFMax, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (GroupOperation, One), (IdRef, One)]),
    inst!(GroupUMax, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (GroupOperation, One), (IdRef, One)]),
    inst!(GroupSMax, [Groups], [(IdType, One), (IdResult, One), (IdScope, One), (GroupOperation, One), (IdRef, One)]),
    inst!(ReadPipe, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(WritePipe, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(ReservedReadPipe, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(ReservedWritePipe, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(ReserveReadPipePackets, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(ReserveWritePipePackets, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(CommitReadPipe, [Pipes], [(IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(CommitWritePipe, [Pipes], [(IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(IsValidReserveId, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(GetNumPipePackets, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GetMaxPipePackets, [Pipes], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GroupReserveReadPipePackets, [Pipes], [(IdType, One), (IdResult, One), (IdScope, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GroupReserveWritePipePackets, [Pipes], [(IdType, One), (IdResult, One), (IdScope, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GroupCommitReadPipe, [Pipes], [(IdScope, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GroupCommitWritePipe, [Pipes], [(IdScope, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(EnqueueMarker, [DeviceEnqueue], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(EnqueueKernel, [DeviceEnqueue], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, ZeroOrMore)]),
    inst!(GetKernelNDrangeSubGroupCount, [DeviceEnqueue], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GetKernelNDrangeMaxSubGroupSize, [DeviceEnqueue], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GetKernelWorkGroupSize, [DeviceEnqueue], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GetKernelPreferredWorkGroupSizeMultiple, [DeviceEnqueue], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(RetainEvent, [DeviceEnqueue], [(IdRef, One)]),
    inst!(ReleaseEvent, [DeviceEnqueue], [(IdRef, One)]),
    inst!(CreateUserEvent, [DeviceEnqueue], [(IdType, One), (IdResult, One)]),
    inst!(IsValidEvent, [DeviceEnqueue], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(SetUserEventStatus, [DeviceEnqueue], [(IdRef, One), (IdRef, One)]),
    inst!(CaptureEventProfilingInfo, [DeviceEnqueue], [(IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(GetDefaultQueue, [DeviceEnqueue], [(IdType, One), (IdResult, One)]),
    inst!(BuildNDRange, [DeviceEnqueue], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One)]),
    inst!(ImageSparseSampleImplicitLod, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSparseSampleExplicitLod, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, One)]),
    inst!(ImageSparseSampleDrefImplicitLod, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSparseSampleDrefExplicitLod, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, One)]),
    inst!(ImageSparseSampleProjImplicitLod, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSparseSampleProjExplicitLod, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, One)]),
    inst!(ImageSparseSampleProjDrefImplicitLod, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSparseSampleProjDrefExplicitLod, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, One)]),
    inst!(ImageSparseFetch, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSparseGather, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSparseDrefGather, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)]),
    inst!(ImageSparseTexelsResident, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One)]),
    inst!(NoLine, [], []),
    inst!(AtomicFlagTestAndSet, [Kernel], [(IdType, One), (IdResult, One), (IdRef, One), (IdScope, One), (IdMemorySemantics, One)]),
    inst!(AtomicFlagClear, [Kernel], [(IdRef, One), (IdScope, One), (IdMemorySemantics, One)]),
    inst!(ImageSparseRead, [SparseResidency], [(IdType, One), (IdResult, One), (IdRef, One), (IdRef, One), (ImageOperands, ZeroOrOne)])
];
